### ISSUE TITLE
ark 0.9.0 deprecated issue

### ISSUE THREAD

**Issue by barracksbuilder** [continuousphp/aws-codedeploy-agent#15]
You are locking to ark 0.9.0 which calls 7-zip as a dependency. 7-zip is deprecated for seven-zip more so 7-zip fails to converge now. Please update the dependency to a newer version of ark.

**Comment by Pierozi** [comment]
Hello @barracksbuilder, Thanks for this reporting, can you open a PR with this fix?

**Comment by barracksbuilder** [comment]
I'm not able to open a private repo on git hub. I haven't fully tested this yet but in your metadata.rb change line 21 from: depends 'ark', '= 0.9.0' TO: depends 'ark'

This will allow you to use the newer ark which no longer depends on 7-zip (replaced with seven-zip).
I am not sure why you are locking to ark 0.9.0 instead of relying on the newest version.

For the time being, I patched 7-zip to fix the kernel check. Now I'm running into a new issue which I think is code deploys issue, not yours.

**Comment by Pierozi** [comment]
Hello, thanks for the details, I will made change and lunch Kitchen test.

> why you are locking to ark 0.9.0 instead

Because at a time of the cookbook was write, it was the latest version.
It's important to specify the version, otherwise you can face unstable installation due to BC break of new version.

**Comment by Pierozi** [comment]
Fix on version `0.7.1`
