### ISSUE TITLE
Version 0.4.1 not on chef supermarket

### ISSUE THREAD

**Issue by wasimkham** [continuousphp/aws-codedeploy-agent#7]
When I try to add the cookbook:

`cookbook 'aws-codedeploy-agent', '~> 0.4.1'`

It throws a version constraint error. It appears that the only version it lets me install is 0.2.0

**Comment by oswaldderiemaecker** [comment]
Right, I didn't found yet the time to update it.

I will update it asap, meanwhile you can use this version, adding this in your Berksfile:

cookbook 'aws-codedeploy-agent', git: 'git://github.com/continuousphp/aws-codedeploy-agent.git'

I'll let open this issue and let you know when it is updated in the chef supermarket.

**Comment by wasimkham** [comment]
Cool thank you.

**Comment by colbywhite-wholefoods** [comment]
FYI: you have the same issue for 0.5.1.

**Comment by colbywhite** [comment]
FYI: you have the same issue for version `0.5.1`

**Comment by oswaldderiemaecker** [comment]
Finally had a little time to work on it, I have removed the version 0.1.0 and 0.2.0, you should now have the latest version 0.6.0 available from the marketplace, be sure to remove the old version from your ~.berkshelf/cookbooks

The version 0.6.0 has been tested on AWS for all supported versions. Also I have also switched to ruby_rbenv to use the rvm download plugin which make the install faster. 

@wasimkham @colbywhite thank you to let me know if I can close the issue.

Your feedback & contribution are welcome!

**Comment by wasimkham** [comment]
Great many thanks!

**Comment by oswaldderiemaecker** [comment]
Great, closing the issue.
